export const ON_PAGE_LOAD = 'ON_PAGE_LOAD'
export const ON_BURGER_CLICKED = 'ON_BURGER_CLICKED'

export const AUTH_WITH_GOOGLE_SUCCESS = 'AUTH_WITH_GOOGLE_SUCCESS'
export const AUTH_WITH_GOOGLE_FAIL = 'AUTH_WITH_GOOGLE_FAIL'
export const AUTH_WITH_SERVER_SUCCESS = 'AUTH_WITH_SERVER_SUCCESS'
export const AUTH_WITH_SERVER_FAIL = 'AUTH_WITH_SERVER_FAIL'
export const AUTH_AUTO_SET_STATE = 'AUTH_AUTO_SET_STATE'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const FETCH_RASPORED_START = 'FETCH_RASPORED_START'
export const FETCH_RASPORED_PREDAVANJA_SUCCESS = 'FETCH_RASPORED_PREDAVANJA_SUCCESS'
export const FETCH_RASPORED_KOLOKVIJUMA_SUCCESS = 'FETCH_RASPORED_KOLOKVIJUMA_SUCCESS'
export const FETCH_RASPORED_ISPITA_SUCCESS = 'FETCH_RASPORED_ISPITA_SUCCESS'
export const FETCH_RASPORED_FAIL = 'FETCH_RASPORED_FAIL'

export const GET_GRUPE_START = 'GET_GRUPE_START'
export const GET_GRUPE_SUCCESS = 'GET_GRUPE_SUCCESS'
export const GET_GRUPE_FAIL = 'GET_GRUPE_FAIL'

export const GET_IZBORNE_START = 'GET_IZBORNE_START'
export const GET_IZBORNE_SUCCESS = 'GET_IZBORNE_SUCCESS'
export const GET_IZBORNE_FAIL = 'GET_IZBORNE_FAIL'

export const GET_IZBORNE_SVE_START = 'GET_IZBORNE_SVE_START'
export const GET_IZBORNE_SVE_SUCCESS = 'GET_IZBORNE_SVE_SUCCESS'
export const GET_IZBORNE_SVE_FAIL = 'GET_IZBORNE_SVE_FAIL'

export const GET_STUDENTI_GRUPE_SUCCESS = 'GET_STUDENTI_GRUPE_SUCCESS'
export const GET_STUDENTI_GRUPE_FAIL = 'GET_STUDENTI_GRUPE_FAIL'
export const GET_STUDENTI_SUCCESS = 'GET_STUDENTI_SUCCESS'
export const GET_STUDENTI_FAIL = 'GET_STUDENTI_FAIL'
export const GET_STUDENTI_GODINA_SUCCESS = 'GET_STUDENTI_GODINA_SUCCESS'
export const GET_STUDENTI_GODINA_FAIL = 'GET_STUDENTI_GODINA_FAIL'

export const GET_ALL_PREDMETI = 'GET_ALL_PREDMETI'

